/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		AAvatar: typeof import('ant-design-vue/es')['Avatar'];
		ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
		ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem'];
		AButton: typeof import('ant-design-vue/es')['Button'];
		ACheckbox: typeof import('ant-design-vue/es')['Checkbox'];
		ACol: typeof import('ant-design-vue/es')['Col'];
		ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
		AForm: typeof import('ant-design-vue/es')['Form'];
		AFormItem: typeof import('ant-design-vue/es')['FormItem'];
		AInput: typeof import('ant-design-vue/es')['Input'];
		AInputPassword: typeof import('ant-design-vue/es')['InputPassword'];
		ALayout: typeof import('ant-design-vue/es')['Layout'];
		ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
		ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
		ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
		AMenu: typeof import('ant-design-vue/es')['Menu'];
		AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
		ARow: typeof import('ant-design-vue/es')['Row'];
		ASelect: typeof import('ant-design-vue/es')['Select'];
		ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
		ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
		ATabPane: typeof import('ant-design-vue/es')['TabPane'];
		ATabs: typeof import('ant-design-vue/es')['Tabs'];
		ATooltip: typeof import('ant-design-vue/es')['Tooltip'];
		Breadcrumb: typeof import('./src/components/business/breadcrumb/index.vue')['default'];
		Header: typeof import('./src/components/single/header/index.vue')['default'];
		HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
		Menu: typeof import('./src/components/single/menu/index.vue')['default'];
		MenuItem: typeof import('./src/components/single/menu/menuItem/index.vue')['default'];
		Mine: typeof import('./src/components/single/header/child/mine/index.vue')['default'];
		ParentView: typeof import('./src/components/commmon/ParentView/index.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		Search: typeof import('./src/components/single/header/child/search/index.vue')['default'];
		Setting: typeof import('./src/components/single/header/child/setting/index.vue')['default'];
		SvgIcon: typeof import('./src/components/commmon/svgIcon/index.vue')['default'];
	}
}
