/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
		ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem'];
		AButton: typeof import('ant-design-vue/es')['Button'];
		ACard: typeof import('ant-design-vue/es')['Card'];
		ACascader: typeof import('ant-design-vue/es')['Cascader'];
		ACol: typeof import('ant-design-vue/es')['Col'];
		ADatePicker: typeof import('ant-design-vue/es')['DatePicker'];
		ADescriptions: typeof import('ant-design-vue/es')['Descriptions'];
		ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem'];
		ADrawer: typeof import('ant-design-vue/es')['Drawer'];
		ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
		AEmpty: typeof import('ant-design-vue/es')['Empty'];
		AForm: typeof import('ant-design-vue/es')['Form'];
		AFormItem: typeof import('ant-design-vue/es')['FormItem'];
		AInput: typeof import('ant-design-vue/es')['Input'];
		AInputNumber: typeof import('ant-design-vue/es')['InputNumber'];
		AInputPassword: typeof import('ant-design-vue/es')['InputPassword'];
		AInputSearch: typeof import('ant-design-vue/es')['InputSearch'];
		ALayout: typeof import('ant-design-vue/es')['Layout'];
		ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
		ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
		ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
		AMenu: typeof import('ant-design-vue/es')['Menu'];
		AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
		AModal: typeof import('ant-design-vue/es')['Modal'];
		APopconfirm: typeof import('ant-design-vue/es')['Popconfirm'];
		AResult: typeof import('ant-design-vue/es')['Result'];
		ARow: typeof import('ant-design-vue/es')['Row'];
		ASelect: typeof import('ant-design-vue/es')['Select'];
		ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
		ASpin: typeof import('ant-design-vue/es')['Spin'];
		ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
		ASwitch: typeof import('ant-design-vue/es')['Switch'];
		ATable: typeof import('ant-design-vue/es')['Table'];
		ATabPane: typeof import('ant-design-vue/es')['TabPane'];
		ATabs: typeof import('ant-design-vue/es')['Tabs'];
		ATextarea: typeof import('ant-design-vue/es')['Textarea'];
		ATimePicker: typeof import('ant-design-vue/es')['TimePicker'];
		ATimeRangePicker: typeof import('ant-design-vue/es')['TimeRangePicker'];
		ATooltip: typeof import('ant-design-vue/es')['Tooltip'];
		ATree: typeof import('ant-design-vue/es')['Tree'];
		ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect'];
		Breadcrumb: typeof import('./src/components/business/breadcrumb/index.vue')['default'];
		Confirm: typeof import('./src/components/commmon/confirm/index.vue')['default'];
		DescHead: typeof import('./src/components/commmon/descHead/index.vue')['default'];
		History: typeof import('./src/components/business/history/index.vue')['default'];
		HistoryItem: typeof import('./src/components/business/history/child/historyItem.vue')['default'];
		Loading: typeof import('./src/components/commmon/loading/index.vue')['default'];
		ModelForm: typeof import('./src/components/commmon/modelForm/index.vue')['default'];
		Page: typeof import('./src/components/commmon/page/index.vue')['default'];
		ParentView: typeof import('./src/components/commmon/ParentView/index.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		Search: typeof import('./src/components/commmon/search/index.vue')['default'];
		SvgIcon: typeof import('./src/components/commmon/svgIcon/index.vue')['default'];
		Table: typeof import('./src/components/commmon/table/index.vue')['default'];
	}
}
